export enum BaseRoutes {
    BaseUrl = 'http://localhost:3000',
    ApiUrl = 'http://ec2-52-59-235-7.eu-central-1.compute.amazonaws.com:8080',
    RestoranImageUrl = 'http://s3.eu-central-1.amazonaws.com/donesi.projekat/restorani/',
    KategorijaImageUrl = 'http://s3.eu-central-1.amazonaws.com/donesi.projekat/kategorije/',
    JeloImageUrl = 'http://s3.eu-central-1.amazonaws.com/donesi.projekat/jela/',
}

export enum AppRoutes {
    Login = '/login',
    Admini = '/admini',
    Feed = '/feed',
    FeedKategorije = '/feed/kategorije',
    AdminKategorije = '/admin/kategorije',
    AdminKategorijeNewImage = '/admin/kategorije/image/:id?',
    Restorani = '/admin/restorani',
    RestoranDetalji = '/restoran/detalji/:id?',
    RestoranKorisniciNew = '/admin/restorani/korisnik-new',
    RestoranKorisnikById = '/admin/restorani/korisnik/:id?',
    RestoranNew = '/admin/restorani/new',
    RestoranById = '/admin/restorani/:id?',
    RestoranNewImage = '/admin/restorani/image/:id?',
    Narudzbe = '/admin/narudzbe',
    PotvrdaNarudzbe = '/narudzbe/potvrda',
    Jela = '/restoran/jela',
    JelaNewImage = '/admin/jela/image/:id?',
    JelaNew = '/restoran/jela/new',
    JeloById = '/restoran/jela/:id?',
    RestoranNarudzbe = '/restoran/narudzbe',
    KategorijaNew = '/admin/kategorije/new',
    AdminNew = '/admini/new',
    AdminById = '/admini/:id?',
    KategorijaById = '/admin/kategorije/:id?',
}
